Try to clarify the text around unmodified
ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs pull request #20
Opened 2021-01-12 23:56 UTC by ekr

This is my attempt to clarify what I said at the microphone.

My point is that the requirement here is that you input IP datagrams in on one end and they come out unmodified on the other end. That doesn't mean that it has to appear unmodified inside QUIC. For instance, one might do header compression inside the channel. It seems like one might have extensions (e.g., NAT or v4/v6 translation) but those affect the exterior interfaces, not the channel.

2021-01-13 00:02 UTC, DavidSchinazi approved these changes
Thanks for writing this!

2021-01-21 09:50 UTC, mirjak requested changes

2021-01-21 15:29 UTC, chris-wood approved these changes

2021-01-21 15:35 UTC, chris-wood commented
@mirjak, since your changes change the meaning of the text, would you mind filing an issue to discuss them? (Editors, please feel free to merge this PR if you think it clarifies things.)

2021-01-21 18:36 UTC, achernya commented
Thanks Chris, given that both David and yourself have approved this change, I'm going to merge this as-is. (Thanks for the change, ekr!) Mirja, please go ahead and open an issue as Chris suggested.

2021-01-21 18:37 UTC, merged

2021-01-21 23:09 UTC, DavidSchinazi commented on draft-ietf-masque-ip-proxy-reqs.md
> +datagrams input on one side and egress them unmodified in their
I think the word unmodified should be kept here