Comments during WGLC
ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs pull request #33
Opened 2021-06-12 01:58 UTC by DavidSchinazi

This PR addresses Magnus' comment about trust and Chris B's comment about MTU.

2021-06-12 13:13 UTC, achernya requested changes

2021-06-12 13:13 UTC, achernya commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
Looking at RFC8085, particularly section 3.1.11, which provides guidance for UDP tunnels, I'm not actually convinced this is the right text or citation. As used here, the proposed transport over MASQUE isn't a UDP tunnel in the strictest sense (at least not like IPIP or GUE), some of the guidance is not directly applicable. For example, things like the Checksum Guidance are probably things that we should now follow unmodified, as the underlying QUIC transport will be using native platform APIs for UDP transmit, and the QUIC framing itself will of course be encrypted and authenticated, making additional application payload CRC (or similar) unnecessary.

It looks like the document that actually describes the fragmentation and PMTUD for tunnels is cited by RFC8085 as INT-TUNNELS, but that seems to be [draft-ietf-intarea-tunnels-03](https://datatracker.ietf.org/doc/html/draft-ietf-intarea-tunnels-03) (since updated to -10).

I'm not sure what to do here citation-wise, because citing an unpublished draft (even though it is cited by a published RFC) seems suboptimal. I don't think citing the entire BCP145/RFC8085 is appropriate, either.

2021-06-14 13:01 UTC, chris-box commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
Alex, I agree the citation ought to be made more precise. I don't see the problem with citing an internet-draft though. RFC8085 does so informatively. Here, even a normative reference would be fine unless we try to take it through the RFC Editor. I assume that's not the plan?

2021-06-14 13:06 UTC, achernya commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
While it's true we're not intending on publishing this particular document, I expect many of the citations that we have here will eventually end up in the implementation drafts, which will go to RFC Editor. If possible I would prefer to avoid citing documents that are still drafts unless they're critical dependencies and we also will be invested in seeing them through to publication in our timeline. We've already had priority inversions with other masque drafts being individual rather than at the WG level; this would be a multi-WG-level citation concern. I'd like to avoid the complexity unless it's absolutely necessary.

2021-06-14 13:32 UTC, chris-box commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
I guess the point here is that when MASQUE is tunnelling IP between networks we need to be careful to do it right.

For example RFC8085 3.1.11 says the actions taken vary depending on whether the tunnelled traffic is already congestion-controlled or not. I presume that for MASQUE-IP it could be carrying a mix of both, although I'm not sure if MASQUE's nature means that the issue doesn't arise.

Similarly RFC8085 3.2, and draft-ietf-intarea-tunnels 4.2.3, discuss PMTU Discovery.

It would be good to get the advice of @gorryfair here. I guess it's a choice between citing one or other document, or writing equivalent text in this draft.

2021-06-14 13:37 UTC, achernya commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
I don't think we should be referencing any of the is-it-already-congestion-controlled bits in RFC8085 3.1.11. To my knowledge there aren't these sorts of considerations for IPSec or VPNs like Wireguard. This is not a point-to-point tunnel in the traditional sense, I as I mentioned in my original comment on this PR.

As to PMTU Discovery, I don't think there's much to say here beyond that the IP proxying requirements need to make it possible to make PMTUD work. In other words, we need to not break it.

All in all, I believe these citations are a net negative, as they bring in concerns that are explicitly not in scope, not relevant, or otherwise handled by our underlying transport.

2021-06-14 17:38 UTC, DavidSchinazi commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
I've switched the BCP145 reference to draft-ietf-intarea-tunnels. Does that work for both of you @chris-box @achernya?

2021-06-14 17:45 UTC, achernya approved these changes

2021-06-14 17:45 UTC, achernya commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
This works for me.

2021-06-15 13:53 UTC, chris-box commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
Yes, me too.

2021-06-15 13:54 UTC, chris-box approved these changes

2021-06-15 15:38 UTC, DavidSchinazi commented on draft-ietf-masque-ip-proxy-reqs.md
> +UDP tunnels in {{?BCP145=RFC8085}}.
Thanks both of you!

2021-06-15 15:38 UTC, merged